# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler via Rcpp
#' @description A random walk Metropolis sampler Rcpp
#' @param sigma  Standard deviation of normal distribution
#' @param x_0 The initial value of iteration
#' @param n  The number of samples
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' x<-RwmsC(2,5,1e5)
#' hist(x)
#' }
#' @export
RwmsC <- function(sigma, x_0, N) {
    .Call('_SC19056_RwmsC', PACKAGE = 'SC19056', sigma, x_0, N)
}

